BUILDDIR=$HOME/build
export VORTEX_ENV="vortex-prebuilt"
export LLVM_PREFIX=$BUILDDIR/vortex-toolchain-prebuilt/llvm-riscv/
export POCL_CC_PATH=$BUILDDIR/vortex-toolchain-prebuilt/pocl/compiler
export POCL_RT_PATH=$BUILDDIR/vortex-toolchain-prebuilt/pocl/runtime
export VERILATOR_ROOT=$BUILDDIR/vortex-toolchain-prebuilt/verilator
export RISCV_TOOLCHAIN_PATH=$BUILDDIR/vortex-toolchain-prebuilt
export PATH="$BUILDDIR/vortex-toolchain-prebuilt/verilator/bin:$PATH"
export PS1="($VORTEX_ENV) $PS1"
